chore(enable): more tips

diff --git a/commands/enable b/commands/enable
--- a/commands/enable
+++ b/commands/enable
@@ -4,7 +4,7 @@ help() {
   echo "Enable a cron service"
   echo ""
   echo "Usage:"
-  echo "  zcron enable [options] [app_name]"
+  echo "  zcron enable [options] <service_name> <service_schedule>"
   echo ""
   echo "Notice:"
   echo "  Use _ instead of * for schedule pattern (bug)"
@@ -24,8 +24,13 @@ core() {
   local service_name=$1
   local service_schedule=${@:2}
 
-  if [ -z "$service_name" ] || [ -z "$service_schedule" ]; then
-    log_error "service name and schedule is required, use --help to get help"
+  if [ -z "$service_name" ]; then
+    log_error "service name is required, use --help to get help"
+    exit 1
+  fi
+
+   if [ -z "$service_schedule" ]; then
+    log_error "service schedule is required, use --help to get help"
     exit 1
   fi
 
